# This configuration file lists supported function nodes under several categories
# All configuration files are stored in the 'config/functions' folder

default:
  - add
  - sub
  - mul
  - mulscalar
  - mod
  - neg
  - max
  - min
  - abs
  - ifelse
  - lerp
  - eq
  - noteq
  - lr
  - gt
  - lreq
  - gteq
  - toint1
  - dot
  - and
  - or
  - not
  - floor
  - ceil
  - sin
  - cos
  - tan
  - atan2
  - sqrt
  - log
  - exp
  - pow2
  - log2
  - cartesian
  - samplecol
  - samplelum
  - passthrough
  - Degrees_to_Turn
  - oneminus
  - ParityTest
  - Pi
  - rotate_position
  - RotationMatrix
  - ScaleMatrix
  - directionToNormal
  - Equality_Boolean
  - '[0_1]_to_[1_0]'
  - GlobalRandom
  - EvenCount
  - OddCount
  - booleanToFloat1
  - deg_to_rad

div: div

swizzle1:
  - swizzle1
  - iswizzle1

swizzle:
  - swizzle2
  - swizzle3
  - swizzle4
  - iswizzle2
  - iswizzle3
  - iswizzle4

vector:
  - vector2
  - vector3
  - vector4
  - ivector2
  - ivector3
  - ivector4

tofloat:
  - tofloat
  - tofloat2
  - tofloat3
  - tofloat4

toint:
  - toint1
  - toint2
  - toint3
  - toint4

const1:
  - const_float1
  - const_int1
  - const_bool

const:
  - const_float2
  - const_float3
  - const_float4
  - const_int2
  - const_int3
  - const_int4

get:
  - get_float1
  - get_float2
  - get_float3
  - get_float4
  - get_integer1
  - get_integer2
  - get_integer3
  - get_integer4
  - get_bool
  - get_string

rand:
  - rand
  - Discrete_[A,B]

set: set
sequence: sequence
