func:
  - ''
  - 'math.atan2({a}[1], {a}[0])'
  - 'torch.atan2({a}.narrow(0, 1, 1), {a}.narrow(0, 0, 1))'
  - 'torch.atan2({a}.narrow(-1, 1, 1), {a}.narrow(-1, 0, 1))'

output_level: [0, 0, 2, 3]

input: [a]

promotion_mask: [False, False, False]

param: null
