func:
  - '[{componentsin}, {componentslast}]'
  - '{componentsin} + {componentslast}'
  - 'torch.cat(({componentsin}, {componentslast}))'
  - 'cat_broadcast(({componentsin}, {componentslast}), dim=-1)'

output_level: [1, 1, 2, 3]

input: [componentsin, componentslast]

promotion_mask: [True, True, True]

param: null
