func: tile_sampler

input:
  background_input: img_bg
  scale_map_input: img_scale
  displacement_map_input: img_disp
  rotation_map_input: img_rotation
  vector_map_input: img_vector
  color_map_input: img_color
  mask_map_input: img_mask
  pattern_distribution_map_input: img_pattern_dist
  pattern_input: img_input_1
  pattern_input_2: img_input_2
  pattern_input_3: img_input_3
  pattern_input_4: img_input_4
  pattern_input_5: img_input_5
  pattern_input_6: img_input_6

output:
  output: ''

param:
- type: integer
  sbs_name: x_amount
  name: x_num
  sbs_default: 16
  scale: [1, 64]
  quantize: True

- type: integer
  sbs_name: y_amount
  name: y_num
  sbs_default: 16
  scale: [1, 64]
  quantize: True

- type: list_index
  sbs_name: pattern
  name: pattern
  default: square
  source_list:
  - none
  - image
  - square
  - disc
  - paraboloid
  - bell
  - gaussian
  - thorn
  - pyramid
  - brick
  - gradation
  - waves
  - half_bell
  - ridged_bell
  - crescent
  - capsule
  - cone
  - gradation_offset

- type: constant
  sbs_name: pattern_input_number
  name: input_number
  default: 1

- type: list_index
  sbs_name: pattern_input_distribution
  name: input_distribution
  default: random
  source_list: [random, cycle, map]

- type: list_index
  sbs_name: pattern_input_filtering
  name: input_filter_mode
  default: bilinear_mipmap
  source_list: [bilinear_mipmap, bilinear, nearest]

- type: default
  sbs_name: pattern_specific
  name: pattern_var
  default: 0.0

- type: default
  sbs_name: pattern_specific_random
  name: pattern_var_random
  default: 0.0

- type: list_index
  sbs_name: pattern_rotation
  name: fixed_rotation
  default: 0
  source_list: [0, 90, 180, 270]

- type: constant
  sbs_name: pattern_rotation_random
  name: fixed_rotation_random
  default: 0.0

- type: constant
  sbs_name: pattern_symmetry_random
  name: symmetry_random
  default: 0.0

- type: list_index
  sbs_name: pattern_symmetry_random_mode
  name: symmetry_random_mode
  default: both
  source_list: [both, horizontal, vertical]

- type: list_index
  sbs_name: size_mode
  name: size_mode
  default: scale
  source_list: [none, scale, scale_square, absolute, pixel]

- type: default
  sbs_name: size
  name: size
  default: [1.0, 1.0]

- type: default
  sbs_name: size_absolute
  name: size_absolute
  default: [0.1, 0.1]

- type: default
  sbs_name: size_pixel
  name: size_pixel
  sbs_default: [1.0, 1.0]
  scale: 4.0

- type: default
  sbs_name: size_random
  name: size_random
  default: [0.0, 0.0]

- type: default
  sbs_name: scale
  name: scale
  sbs_default: 0.8
  scale: 10.0

- type: default
  sbs_name: scale_random
  name: scale_random
  default: 0.0

- type: default
  sbs_name: scale_map_multiplier
  name: scale_map
  default: 0.0

- type: default
  sbs_name: scale_vector_map_multiplier
  name: scale_vector_map
  default: 0.0

- type: list_index
  sbs_name: scale_parametrization_affect
  name: scale_map_effect
  default: both
  source_list: [both, x, y]

- type: default
  sbs_name: position_random
  name: position_random
  default: 0.0
  scale: 10.0

- type: default
  sbs_name: offset
  name: offset
  default: 0.0

- type: list_index
  sbs_name: offset_type
  name: offset_type
  default: x_alt
  source_list: [x_alt, y_alt, x_global, y_global]

- type: default
  sbs_name: global_offset
  name: global_offset
  default: [0.0, 0.0]

- type: default
  sbs_name: displacement_map_intensity
  name: disp_map
  default: 0.0

- type: default
  sbs_name: displacement_angle
  name: disp_angle
  default: 0.0

- type: default
  sbs_name: vector_map_displacement
  name: disp_vector_map
  default: 0.0

- type: default
  sbs_name: rotation
  name: rotation
  default: 0.0

- type: default
  sbs_name: rotation_random
  name: rotation_random
  default: 0.0

- type: default
  sbs_name: rotation_map_multiplier
  name: rotation_map
  default: 0.0

- type: default
  sbs_name: rotation_vector_map_multiplier
  name: rotation_vector_map
  default: 0.0

- type: constant
  sbs_name: mask_map_threshold
  name: mask_map_threshold
  default: 0.0

- type: constant
  sbs_name: mask_map_invert
  name: mask_map_invert
  default: False

- type: list_index
  sbs_name: mask_map_sampling_technique
  name: mask_map_sampling
  default: center
  source_list: [center, bbox]

- type: constant
  sbs_name: mask_random
  name: mask_random
  default: 0.0

- type: constant
  sbs_name: mask_invert
  name: mask_invert
  default: False

- type: list_index
  sbs_name: blending_mode
  name: blending_mode
  default: max
  source_list: [add_sub, max]

- type: default
  sbs_name: color
  name: color
  default: 1.0

- type: default
  sbs_name: color_random
  name: color_random
  default: 0.0

- type: list_index
  sbs_name: color_parametrization_mode
  name: color_scale_mode
  default: input
  source_list: [input, scale, row, column, number]

- type: default
  sbs_name: color_parametrization_multiplier
  name: color_scale
  default: 0.0

- type: default
  sbs_name: global_opacity
  name: global_opacity
  default: 1.0

- type: default
  sbs_name: background_color
  name: background_color
  default: 0.0

- type: constant
  sbs_name: reverse_rendering_order
  name: reverse_order
  default: False
