func: anisotropic_blur

input:
  Source: img_in

output:
  Anisotropic_Blur: ''

param:
- type: constant
  sbs_name: Quality
  name: high_quality
  default: False

- type: default
  sbs_name: Intensity
  name: intensity
  sbs_default: 10.0
  scale: 16.0

- type: default
  sbs_name: Anisotropy
  name: anisotropy
  sbs_default: 0.5

- type: default
  sbs_name: Angle
  name: angle
  sbs_default: 0.0