func: color_blend

input:
  Foreground: img_fg
  Background: img_bg
  Mask: mask

output:
  Color: ''

param:
- type: default
  sbs_name: Opacity
  name: opacity
  sbs_default: 1.0

- type: constant
  sbs_name: Alpha_Blending
  name: alpha_blending
  default: True
