func: d_blur

input:
  input1: img_in

output: null

param:
- type: default
  sbs_name: intensity
  name: intensity
  sbs_default: 10.0
  scale: 20.0

- type: default
  sbs_name: mblurangle
  name: angle
  sbs_default: 0.0