func: hbao

input:
  input: img_in

output:
  output: ''

param:
- type: constant
  sbs_name: use_world_units
  name: world_units
  default: False

- type: constant
  sbs_name: samples
  name: quality
  default: 8

- type: default
  sbs_name: surface_size
  name: surface_size
  sbs_default: 300.0
  scale: 1000.0

- type: default
  sbs_name: height_depth_cm
  name: height_cm
  sbs_default: 30.0
  scale: 1000.0

- type: default
  sbs_name: height_depth
  name: depth
  sbs_default: 0.1

- type: default
  sbs_name: radius
  name: radius
  sbs_default: 1.0