func: histogram_select

input:
  input: img_in

output:
  output: ''

param:
- type: default
  sbs_name: position
  name: position
  sbs_default: 0.5

- type: default
  sbs_name: range
  name: ranges
  sbs_default: 0.25

- type: default
  sbs_name: constrast
  name: contrast
  sbs_default: 0.0