func: hsl

input:
  input1: img_in

output: null

param:
- type: default
  sbs_name: hue
  name: hue
  sbs_default: 0.5

- type: default
  sbs_name: saturation
  name: saturation
  sbs_default: 0.5

- type: default
  sbs_name: luminosity
  name: lightness
  sbs_default: 0.5