func: multi_switch

input:
  input_1: input_1
  input_2: input_2
  input_3: input_3
  input_4: input_4
  input_5: input_5
  input_6: input_6
  input_7: input_7
  input_8: input_8
  input_9: input_9
  input_10: input_10
  input_11: input_11
  input_12: input_12
  input_13: input_13
  input_14: input_14
  input_15: input_15
  input_16: input_16
  input_17: input_17
  input_18: input_18
  input_19: input_19
  input_20: input_20

output:
  output: ''

param:
  - type: constant
    sbs_name: input_number
    name: input_number
    default: 2

  - type: constant
    sbs_name: input_selection
    name: input_selection
    default: 1
