func: non_square_transform

input:
  input: img_in

output:
  output: ''

param:
- type: list_index
  sbs_name: tile_mode
  name: tile_mode
  default: automatic
  source_list: [automatic, manual]

- type: integer
  sbs_name: tile
  name: tile
  sbs_default: [1, 1]
  scale: [1, 16]

- type: constant
  sbs_name: tile_safe_rotation
  name: tile_safe_rotation
  sbs_default: True

- type: default
  sbs_name: offset
  name: offset
  sbs_default: [0.0, 0.0]

- type: default
  sbs_name: rotation
  name: rotation
  sbs_default: 0.0

- type: default
  sbs_name: background_color
  name: background_color
  sbs_default: [0.0, 0.0, 0.0, 1.0]
