func: replace_color

input:
  Input: img_in

output:
  ToTargetColor: ''

param:
- type: default
  sbs_name: SourceColor
  name: source_color
  sbs_default: [0.5, 0.5, 0.5]

- type: default
  sbs_name: TargetColor
  name: target_color
  sbs_default: [0.5, 0.5, 0.5]