func: shadows

input:
  Input: img_in

output:
  shadows: ''

param:
- type: default
  sbs_name: shadow_distance
  name: dist
  sbs_default: 0.3

- type: default
  sbs_name: light_angle
  name: light_angle
  sbs_default: 0.13

- type: default
  sbs_name: edge_softness
  name: edge_softness
  sbs_default: 1.0

- type: constant
  sbs_name: Samples
  name: samples
  sbs_default: 8
